controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
feed_rss:
    path: /rss
    controller: App\Controller\FeedController::getRssFeedAction
    methods: GET
index:
    path: /
    controller: App\Controller\DefaultController::index
